baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My Hugo Blog'
theme = 'PaperMod'

[taxonomies]
tag = 'tags'
category = 'categories'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [['$$', '$$']]
delimiters.inline = [['$', '$']]

[params]
description = 'A personal blog'
author = 'Your Name'
