baseURL = 'https://blog.xinliu.uk/'
locale = 'en-us'
title = 'Blog of Xin'
theme = 'PaperMod'

[taxonomies]
tag = 'tags'
category = 'categories'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [['$$', '$$']]
delimiters.inline = [['$', '$']]

[params]
description = 'A personal blog'
author = 'Xin Liu'
keywords = ['blog', 'Mathematics', 'Finance']

# Profile / Bio
[params.profile]
enabled = true
avatar = ''  # leave empty for initial, set URL later
name = 'Xin Liu'
tagline = 'Mathematics & Finance'
bio = 'I came; I saw; I conquered.'

# Social links

[[params.social]]
name = 'Email'
icon = 'mail'
url = 'mailto:xinliu2861@gmail.com'

# Site info
[params.siteInfo]
hideFooter = true

# Home page config
[params.homeInfoParams]
enabled = true
